### ISSUE TITLE
Add 팀리스트 페이지 구현

### ISSUE THREAD

**Issue by M1zz** [ProjectInTheClass/TeamNine#3]
### TODO:
사용자가 원하는 운동의 리스트를 테이블 뷰로 그려야합니다.

- [x] 리스트 전부 그리기
- [x] 데이터가 있으면 테이블로 그리기
- [x] 셀을 누르면 해당 뷰로 이동

화면은 아래와 같습니다.
화면 : 
#
